name: Colosseum Gradle Plugin
description: Colosseum Gradle Plugin

inputs:
  build-ref:
    description: Ref
    required: true
  java-distribution:
    description: Java distribution
    required: false
    default: "temurin"
  maven:
    description: Maven url
    required: true
  maven-username:
    description: Maven login username
    required: true
  maven-password:
    description: Maven login password
    required: true
  artifact-retention-days:
    description: Jar artifact retention days
    required: false
    default: "1"


runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        repository: "NetherRealmSpigot/ColosseumGradle"
        ref: ${{ inputs.build-ref }}
        fetch-depth: 0

    - uses: actions/setup-java@v4
      with:
        java-version: "8"
        distribution: ${{ inputs.java-distribution }}

    - uses: gradle/actions/setup-gradle@v3

    - run: ./gradlew build
      shell: bash
    
    - uses: mikepenz/action-junit-report@v5
      if: ${{ success() || failure() }}
      with:
        report_paths: './build/test-results/test/TEST-*.xml'
        include_passed: true
        detailed_summary: true
        fail_on_failure: true
        require_tests: true
        check_name: Test Report (Ref ${{ inputs.build-ref }})
        check_title_template: '{{SUITE_NAME}} | {{TEST_NAME}}'
    
    - run: ./gradlew publish
      shell: bash
      id: publish-plugin-jar
      if: ${{ (github.ref_name == 'master' && github.event_name == 'push') || github.event_name == 'workflow_dispatch' }}
      env:
        COLOSSEUM_MAVEN_URL: ${{ inputs.maven }}
        COLOSSEUM_MAVEN_USERNAME: ${{ inputs.maven-username }}
        COLOSSEUM_MAVEN_PASSWORD: ${{ inputs.maven-password }}
      continue-on-error: true
    
    - uses: actions/upload-artifact@v4
      if: ${{ steps.publish-plugin-jar.outcome != 'success' || github.event_name == 'workflow_dispatch' }}
      with:
        name: Colosseum-plugin-${{ github.run_id }}
        path: ./build/libs/*.jar
        retention-days: ${{ inputs.artifact-retention-days }}
        overwrite: true
      continue-on-error: true